// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdbkcjbgjqnbmznxobjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkYmtjamJnanFuYm16bnhvYmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTY1NTIsImV4cCI6MjA2MDAzMjU1Mn0.yMjafay-ju5UtnApmuQHHZ1Ygw3nQn7PPWVju0YjVeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);